language: rust
rust: nightly
cache: cargo
script:
  - cargo build --release

os:
  - linux
#  - osx
#  - windows

before_deploy:
  - cd $TRAVIS_BUILD_DIR

deploy:
  verbose: true
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  #local_dir: target/release
  on:
    branch: master
